never-stop-stopping-1.jpg:
  caption: Amala Antony and Huan Ziqi, 2019<br>MA Graphic Media Design, LCC
  alt: A face with large eyes is projected over the top of the face of a young woman with long hair.
never-stop-stopping-2.jpg:
  caption: Paloma Moniz, Ricardo Gonçalves, Roxy Zeiher<br>MA Graphic Media Design, LCC
  alt: A man with a short beard and unkempt hair is wearing a grey suit and pointing enthusiastically.
never-stop-stopping-3.jpg:
  caption: Paloma Moniz, Ricardo Gonçalves, Roxy Zeiher<br>MA Graphic Media Design, LCC
  alt: A tall, thin white book with the words 'Premium Hustler Vol. 1' printed on it.
never-stop-stopping-4.jpg:
  caption: Qiong Zhao and Xinyi Wang, 2019<br>MA Graphic Media Design, LCC
  alt: A projection of a young woman in a white T-shirt eating a cherry. There is a small white sensor stuck to her temple.
never-stop-stopping-5.jpg:
  caption: 
  alt: A keyboard and mouse with more than 20 computer monitors displaying complex trading diagrams