WaluigisPurgatory_A.jpg:
  caption: "Roma Europa Festival, Rome"
  alt: 
WaluigisPurgatory_B.jpg:
  caption: "Robot Festival, Bologna"
  alt: 
WaluigisPurgatory_C.jpg:
  caption: "Roma Europa Festival, Rome"
  alt: 
WaluigisPurgatory_C.jpg:
  caption: "HQI, London"
  alt: 
WaluigisPurgatory_A.jpg:
  caption: "East London Art Prize, Nunnery Gallery"
  alt:
