WaluigisPurgatory_A.jpg:
  caption: "Roma Europa Festival, Rome"
WaluigisPurgatory_B.jpg:
  caption: "Robot Festival, Bologna"
WaluigisPurgatory_C.jpg:
  caption: "Roma Europa Festival, Rome"
WaluigisPurgatory_C.jpg:
  caption: "HQI, London"
WaluigisPurgatory_A.jpg:
  caption: "East London Art Prize, Nunnery Gallery"