WaluigisPurgatory_A.jpg:
  caption: "Mattatoio, Rome"
WaluigisPurgatory_B.jpg:
  caption: "San Barbaziano, Bologna"
WaluigisPurgatory_C.jpg:
  caption: "Mattatoio, Rome"
WaluigisPurgatory_J.jpg:
  caption: "HQI, London"
WaluigisPurgatory_K.jpg:
  caption: "Nunnery Gallery, London"