a.jpg:
  caption: SOLO CSV, Madrid
b.jpg:
  caption: SOLO CSV, Madrid
c.jpg:
  caption: SOLO CSV, Madrid
d.jpg:
  caption: SOLO CSV, Madrid
e.jpg:
   caption: SOLO CSV, Madrid
e2.jpg:
   caption: SOLO CSV, Madrid
h.jpg:
  caption: Tecnopolo, Bologna
i.jpg:
  caption: Tecnopolo, Bologna