OffshoreInvestigationVehicle_A.jpg:
  caption: "Photo: Domen Pal / Aksioma"
OffshoreInvestigationVehicle_B.jpg:
  caption: "Photo: Domen Pal / Aksioma"
OffshoreInvestigationVehicle_C.jpg:
  caption: "Photo: Domen Pal / Aksioma"
OffshoreInvestigationVehicle_D.jpg:
  caption: "Photo: Domen Pal / Aksioma"
OffshoreInvestigationVehicle_E.jpg:
  caption: "Photo: Domen Pal / Aksioma"
OffshoreInvestigationVehicle_F.jpg:
  caption: "Profit For All performance at Transmediale 2018"
OffshoreInvestigationVehicle_G.jpg:
  caption: "Photo: Domen Pal / Aksioma"
OffshoreInvestigationVehicle_H.jpg:
  caption: ""
