OffshoreInvestigationVehicle_1.jpg:
  caption: "HKW, Berlin"
OffshoreInvestigationVehicle_2.jpg:
  caption: "HKW, Berlin"
OffshoreInvestigationVehicle_3.jpg:
  caption: "Aksioma, Ljubljana"
OffshoreInvestigationVehicle_4.jpg:
  caption: "Aksioma, Ljubljana"
OffshoreInvestigationVehicle_5.jpg:
  caption: "Aksioma, Ljubljana"
OffshoreInvestigationVehicle_6.jpg:
  caption: "Aksioma, Ljubljana"
OffshoreInvestigationVehicle_7.jpg:
  caption: "Aksioma, Ljubljana"
OffshoreInvestigationVehicle_8.jpg:
  caption: "Vilém Flusser Archiv, Berlin"
OffshoreInvestigationVehicle_9.jpg:
  caption: "HKW, Berlin"
