const minify = require('html-minifier').minify;
const minify_opts = {
  caseSensitive: true,
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: false,
  collapseWhitespace: true,
  conservativeCollapse: false,
  continueOnParseError: false,
  decodeEntities: false, //Use direct Unicode characters whenever possible
  html5: true, 	//Parse input according to HTML5 specifications 	true
  includeAutoGeneratedTags: true,
  keepClosingSlash: false,
  preserveLineBreaks: false,
  preventAttributesEscaping: false,
  processConditionalComments: false,
  quoteCharacter: '"',
  removeAttributeQuotes: false,
  removeComments: true,
  removeEmptyAttributes: true,
  removeEmptyElements: false,
  removeOptionalTags: false,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  removeTagWhitespace: false,
  sortAttributes: false,
  sortClassName: false,
  useShortDoctype: true,
  minifyJS: true
};

module.exports = function( html ){
  return minify( html, minify_opts );
}