Network-Ensemble-1.jpg:
  caption: NEX, a phone powered wifi sniffer able to translate data packets into sound
  alt: A small black X shaped machine with a red X on top. 2 buttons on the left hand side and some circuitry on top
Network-Ensemble-2.jpg:
  caption: NE3, a wifi sniffer able to translate data packets into sound
  alt: A flat black device with two audio ports, a switch and white circuitry on top. A short black aerial is coming out the top.
Network-Ensemble-3.jpg:
  caption: NE3, a wifi sniffer able to translate data packets into sound
  alt: A flat black device with two audio ports, a switch and white circuitry on top. A short black aerial is coming out the top.
Network-Ensemble-4.jpg:
  caption: Flash Demons, released in 2019 by MILLE PLATEAUX 
  alt: A red and black object, vacuum packaged in clear plastic. There is text that says 'Flash Demons' and 'Network Ensemble' printed on the front.
Network-Ensemble-5.jpg:
  caption: Flash Demons, released in 2019 by MILLE PLATEAUX 
  alt: A red and black object, vacuum packaged in clear plastic. There is text that says 'Flash Demons' and 'Network Ensemble' printed on the front.
Network-Ensemble-6.jpg:
  caption: Selected Network Studies, released in 2016 by NUKFM
  alt: A small silver packet with something inside and the words 'Selected Network Studies. Network Ensemble' printed on the front.
Network-Ensemble-7.jpg:
  caption: Selected Network Studies, released in 2016 by NUKFM
  alt: A small silver packet with something inside and the words 'Selected Network Studies. Network Ensemble' printed on the front.