Network-Ensemble-1.jpg:
  caption:
  alt: A small black X shaped machine with a red X on top. 2 buttons on the left hand side and some circuitry on top
Network-Ensemble-2.jpg:
  caption:
  alt: A flat black device with two audio ports, a switch and white circuitry on top. A short black aerial is coming out the top.
Network-Ensemble-3.jpg:
  caption: 
  alt: Screenshot of a terminal window on a computer with the words 'Network Controler at the top' and a table of complex numbers and diagrams.
Network-Ensemble-4.jpg:
  caption:
  alt: A red and black object, vacuum packaged in clear plastic. There is text that says 'Flash Demons' and 'Network Ensemble' printed on the front.
Network-Ensemble-5.jpg:
  caption:
  alt: A small silver packet with something inside and the words 'Selected Network Studies. Network Ensemble' printed on the front.
  Network-Ensemble-6.jpg:
  caption:
  alt: Many small silver packets with something inside scattered over each other. The words 'Selected Network Studies. Network Ensemble' printed on the front pf each.