a.jpg:
  caption: Edinburgh Art Festival 
b.jpg:
  caption: Edinburgh Art Festival
c.jpg: 
  caption: Edinburgh Art Festival
d.jpg: 
  caption: Edinburgh Art Festival
n.jpg: 
  caption: Edinburgh Art Festival
o.jpg: 
  caption: Edinburgh Art Festival