1.jpg:  
  caption: Christine Meyer and Anita Nguyen, MA Visuelle Kommunikation, Weissensee
  alt: ALT Christine Meyer and Anita Nguyen, MA Visuelle Kommunikation, Weissensee
2.jpg: 
  caption: Ezequiel Hyon, BA Visuelle Kommunikation, Weissensee
  alt: ALT Ezequiel Hyon, BA Visuelle Kommunikation, Weissensee
4.jpg:  
  caption: Leon Schöler, MA Visuelle Kommunikation, Weissensee
  alt: ALT Leon Schöler, MA Visuelle Kommunikation, Weissensee
5.jpg:
  caption: Jason Yang, MA Moving Image, Ravensbourne University London
  alt: ALT Jason Yang, MA Moving Image, Ravensbourne University London
6.png:  
  caption: 
  alt: ALT six dot png