Plane-of-Theseus-1.jpg:  
  caption: Christine Meyer and Anita Nguyen, 2019<br>MA Visuelle Kommunikation, Weissensee
  alt: A website with a cloud image in the background and the words 'Crisis Control, the Customers are waiting'
Plane-of-Theseus-2.jpg:  
  caption: Judith Weber, 2019<br>MA Visuelle Kommunikation, Weissensee
  alt: An artificial landscape with the words 'safe space' and drawings of yellow rocks overlaid
Plane-of-Theseus-3.jpg:  
  caption: Leon Schöler, 2019<br>MA Visuelle Kommunikation, Weissensee
  alt: An aircraft flying through dollar signs and oil barrels
Plane-of-Theseus-4.jpg:  
  caption: Yael Ohmer and Anneliese Wabnitz, 2019<br>MA Visuelle Kommunikation, Weissensee
  alt: A smiling aircraft with a whale's tail surrounded by the words Boeing 7-3-7
Plane-of-Theseus-5.jpg: 
  caption: Ezequiel Hyon, 2019<br>MA Visuelle Kommunikation, Weissensee
  alt: Black and white, mri-style scans of the components of an aircraft
Plane-of-Theseus-6.jpg: 
  caption: ''
  alt: key dates in the production and development of an aeroplane obscured by a quote saying 'ideas are measured in dollars' - managers at boeing