FLASH-1.jpg:
  caption: FLASH, part of Network Ensemble, Gluqbar, Milan
  alt: ALT FLASH, part of Network Ensemble, Gluqbar, Milan
FLASH-2.jpg:
  caption: FLASH, part of Network Ensemble, Gluqbar, Milan
  alt: ALT FLASH, part of Network Ensemble, Gluqbar, Milan