Offshore-Investigation-Vehicle-A.jpg:
  caption: Available as a PDF
  alt: ALT The Offshore Investigation Vehicle is available as a PDF
Offshore-Investigation-Vehicle-B.jpg:
  caption: 
  alt: ALT 
Offshore-Investigation-Vehicle-C.jpg:
  caption: 
  alt: ALT 
Offshore-Investigation-Vehicle-D.jpg:
  caption: 
  alt: ALT 
Offshore-Investigation-Vehicle-E.jpg:
  caption: 
  alt: ALT 
Offshore-Investigation-Vehicle-G.jpg:
  caption: 
  alt: ALT 
Offshore-Investigation-Vehicle-H.jpg:
  caption: 
  alt: ALT 
Offshore-Investigation-Vehicle-I.jpg:
  caption: 
  alt: ALT 
Offshore-Investigation-Vehicle-J.jpg:
  caption: 
  alt: ALT 