GODMODE_ep1_A.jpg:
  caption: "WSA, New York City"
GODMODE_ep1_B.jpg:
  caption: "Theatro Circo, Braga"
GODMODE_ep1_D.jpg:
  caption: "HQI, London"
GODMODE_ep1_E.jpg:
  caption: "HQI, London"
GODMODE_ep1_E2.jpg:
  caption: "HQI, London"
GODMODE_ep1_N.jpg:
  caption: "System, Shanghai"