GODMODE_ep1_A.jpg:
  caption: "WSA, New York"
GODMODE_ep1_B.jpg:
  caption: "Semibreve, Theatro Circo, Braga"
GODMODE_ep1_C.jpg:
  caption: "Serpentine, London"
GODMODE_ep1_D.jpg:
  caption: "Serpentine, London"
GODMODE_ep1_E.jpg:
  caption: "Serpentine, London"
GODMODE_ep1_M.jpg:
  caption: "System, Shanghai"